[package]
name = "binary-options"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmwasm-std = { version = "1.5.4", features = ["stargate"] }
cw-storage-plus = "1.2.0"
cosmwasm-schema = "1.5.4"
prost = "0.13.4"


[lib]
crate-type = ["cdylib"]