[package]
name = "my-randomness-contract"
version = "0.1.0"
edition = "2021"
description = "A CosmWasm contract that implements an event manager + randomness generator"

[dependencies]
cosmwasm-std = "1.1.0"
cw2 = "0.14.0"
cw-storage-plus = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
schemars = "0.8"

[lib]
crate-type = ["cdylib"]